const STORAGE_KEY="atm-simulator-v1";
const defaultData={accounts:[{number:"10010001",name:"Demo Customer",pin:"1234",balance:25000,status:"active"}],transactions:[]};
let data=loadData(),currentAccount=null,failedAttempts=0;
const $=id=>document.getElementById(id);
function loadData(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(defaultData)}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function money(v){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(v)}
function showToast(msg){$("toast").textContent=msg;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2400)}
function message(id,msg="",ok=false){$(id).textContent=msg;$(id).style.color=ok?"#147a4b":""}
function account(){return data.accounts.find(a=>a.number===currentAccount)}
function switchPanel(panel){document.querySelectorAll(".panel").forEach(p=>p.classList.add("hidden"));$(panel+"Panel").classList.remove("hidden");document.querySelectorAll(".menu-btn").forEach(b=>b.classList.toggle("active",b.dataset.panel===panel));renderHistory()}
function render(){const a=account();$("welcomeName").textContent=a.name;$("accountBadge").textContent="A/C •••• "+a.number.slice(-4);$("balance").textContent=money(a.balance);renderHistory()}
function addTransaction(type,amount,balance,details=""){data.transactions.unshift({id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(),account:currentAccount,type,amount,balance,date:new Date().toISOString(),details});save();render()}
function renderHistory(){if(!currentAccount)return;const rows=data.transactions.filter(t=>t.account===currentAccount);$("historyBody").innerHTML=rows.length?rows.map(t=>{const debit=["Withdrawal","Transfer"].includes(t.type);return "<tr><td>"+new Date(t.date).toLocaleString()+"</td><td>"+t.type+"</td><td class='"+(debit?"debit":"credit")+"'>"+(debit?"−":"+")+money(t.amount)+"</td><td>"+money(t.balance)+"</td><td>"+escapeHtml(t.details||"—")+"</td></tr>"}).join(""):"<tr><td colspan='5'>No transactions yet.</td></tr>"}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function validAmount(v){return Number.isFinite(v)&&v>0}
$("loginForm").addEventListener("submit",e=>{e.preventDefault();const n=$("accountNumber").value.trim(),p=$("pin").value.trim(),a=data.accounts.find(x=>x.number===n);if(failedAttempts>=3){message("loginMessage","Too many failed attempts. Refresh the page to reset the demo.");return}if(!a||a.pin!==p||a.status!=="active"){failedAttempts++;message("loginMessage","Invalid credentials. "+(3-failedAttempts)+" attempt(s) remaining.");return}failedAttempts=0;currentAccount=n;$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");render();showToast("Authentication successful")});
$("logoutBtn").addEventListener("click",()=>{currentAccount=null;$("appView").classList.add("hidden");$("loginView").classList.remove("hidden");$("loginForm").reset();showToast("Session ended")});
document.addEventListener("click",e=>{const b=e.target.closest("[data-panel]");if(b)switchPanel(b.dataset.panel);const amt=e.target.closest("[data-amount]");if(amt)$("withdrawAmount").value=amt.dataset.amount});
$("withdrawForm").addEventListener("submit",e=>{e.preventDefault();const amount=Number($("withdrawAmount").value),a=account();message("withdrawMessage");if(!validAmount(amount)||amount%100!==0){message("withdrawMessage","Enter a positive withdrawal amount in multiples of ₹100.");return}if(amount>a.balance){message("withdrawMessage","Insufficient funds.");return}a.balance-=amount;addTransaction("Withdrawal",amount,a.balance,"Cash withdrawal");$("withdrawForm").reset();message("withdrawMessage","Withdrawal successful.",true);showToast("Withdrawal completed")});
$("depositForm").addEventListener("submit",e=>{e.preventDefault();const amount=Number($("depositAmount").value),a=account();message("depositMessage");if(!validAmount(amount)){message("depositMessage","Enter a valid deposit amount.");return}a.balance+=amount;addTransaction("Deposit",amount,a.balance,"Cash deposit");$("depositForm").reset();message("depositMessage","Deposit successful.",true);showToast("Deposit completed")});
$("transferForm").addEventListener("submit",e=>{e.preventDefault();const dest=$("destinationAccount").value.trim(),amount=Number($("transferAmount").value),a=account(),target=data.accounts.find(x=>x.number===dest);message("transferMessage");if(!target){message("transferMessage","Destination account was not found.");return}if(dest===currentAccount){message("transferMessage","You cannot transfer to your own account.");return}if(!validAmount(amount)){message("transferMessage","Enter a valid transfer amount.");return}if(amount>a.balance){message("transferMessage","Insufficient funds.");return}a.balance-=amount;target.balance+=amount;addTransaction("Transfer",amount,a.balance,"To "+dest);$("transferForm").reset();message("transferMessage","Transfer successful.",true);showToast("Transfer completed")});
$("pinForm").addEventListener("submit",e=>{e.preventDefault();const cur=$("currentPin").value,n=$("newPin").value,c=$("confirmPin").value,a=account();message("pinMessage");if(cur!==a.pin){message("pinMessage","Current PIN is incorrect.");return}if(!/^\d{4,6}$/.test(n)){message("pinMessage","New PIN must contain 4–6 digits.");return}if(n!==c){message("pinMessage","New PIN and confirmation do not match.");return}a.pin=n;save();$("pinForm").reset();message("pinMessage","PIN updated successfully.",true);showToast("PIN changed")});
$("clearHistoryBtn").addEventListener("click",()=>{const rows=data.transactions.filter(t=>t.account===currentAccount);if(!rows.length)return;data.transactions=data.transactions.filter(t=>t.account!==currentAccount);save();renderHistory();showToast("Transaction history cleared")});
